apiVersion: apps/v1
kind: Deployment
metadata:
  name: coll-f7b34085c9f4434eb5806d34facc5978-depl
  labels:
    app: coll-f7b34085c9f4434eb5806d34facc5978
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coll-f7b34085c9f4434eb5806d34facc5978
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: coll-f7b34085c9f4434eb5806d34facc5978
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      serviceAccountName: alloy-service-account
      volumes:
        - name: alloy-config
          configMap:
            name: alloy-configmap
            items:
              - key: alloy.river
                path: config.alloy

        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
      containers:
        - name: coll-f7b34085c9f4434eb5806d34facc5978
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:coll-f7b34085c9f4434eb5806d34facc5978
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping


        - name: alloy-sidecar
          image: grafana/alloy:latest
          args:
            - "run"
            - "/etc/alloy/config.alloy"
            - "--server.http.listen-addr=0.0.0.0:12345"
          ports:
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
            - name: alloy-http
              containerPort: 12345
              protocol: TCP
          volumeMounts:
            - name: alloy-config
              mountPath: /etc/alloy
            - name: podinfo
              mountPath: /etc/podinfo
              readOnly: true
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"